/* pedrosh-getopt.h */

/* File autogenerated by gengetopt version 2.10  */

#ifndef PEDROSH_GETOPT_H
#define PEDROSH_GETOPT_H

/* If we use autoconf.  */
#ifdef HAVE_CONFIG_H
#include "config.h"
#endif

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

#ifndef CMDLINE_PARSER_PACKAGE
#define CMDLINE_PARSER_PACKAGE PACKAGE
#endif

#ifndef CMDLINE_PARSER_VERSION
#define CMDLINE_PARSER_VERSION VERSION
#endif

struct gengetopt_args_info
{
  char * mgmtfs_arg;	/* path to the management file system directory.  */
  int testing_stub_flag;	/* use stub handler instead of ipc handler (default=off).  */

  int help_given ;	/* Whether help was given.  */
  int version_given ;	/* Whether version was given.  */
  int mgmtfs_given ;	/* Whether mgmtfs was given.  */
  int testing_stub_given ;	/* Whether testing-stub was given.  */

  char **inputs ; /* unamed options */
  unsigned inputs_num ; /* unamed options number */
} ;

int cmdline_parser (int argc, char * const *argv, struct gengetopt_args_info *args_info);

void cmdline_parser_print_help(void);
void cmdline_parser_print_version(void);

#ifdef __cplusplus
}
#endif /* __cplusplus */
#endif /* PEDROSH_GETOPT_H */
